#include <iostream>
#include "syscall.hpp"


SysCallId arm64_canonicalize_syscall(ARM64_SYSCALL syscall_number)
{
    switch (syscall_number)
    {
      case ARM64_SYSCALL::IO_SETUP:
        return SysCallId::IO_SETUP;
      case ARM64_SYSCALL::IO_DESTROY:
        return SysCallId::IO_DESTROY;
      case ARM64_SYSCALL::IO_SUBMIT:
        return SysCallId::IO_SUBMIT;
      case ARM64_SYSCALL::IO_CANCEL:
        return SysCallId::IO_CANCEL;
      case ARM64_SYSCALL::IO_GETEVENTS:
        return SysCallId::IO_GETEVENTS;
      case ARM64_SYSCALL::SETXATTR:
        return SysCallId::SETXATTR;
      case ARM64_SYSCALL::LSETXATTR:
        return SysCallId::LSETXATTR;
      case ARM64_SYSCALL::FSETXATTR:
        return SysCallId::FSETXATTR;
      case ARM64_SYSCALL::GETXATTR:
        return SysCallId::GETXATTR;
      case ARM64_SYSCALL::LGETXATTR:
        return SysCallId::LGETXATTR;
      case ARM64_SYSCALL::FGETXATTR:
        return SysCallId::FGETXATTR;
      case ARM64_SYSCALL::LISTXATTR:
        return SysCallId::LISTXATTR;
      case ARM64_SYSCALL::LLISTXATTR:
        return SysCallId::LLISTXATTR;
      case ARM64_SYSCALL::FLISTXATTR:
        return SysCallId::FLISTXATTR;
      case ARM64_SYSCALL::REMOVEXATTR:
        return SysCallId::REMOVEXATTR;
      case ARM64_SYSCALL::LREMOVEXATTR:
        return SysCallId::LREMOVEXATTR;
      case ARM64_SYSCALL::FREMOVEXATTR:
        return SysCallId::FREMOVEXATTR;
      case ARM64_SYSCALL::GETCWD:
        return SysCallId::GETCWD;
      case ARM64_SYSCALL::LOOKUP_DCOOKIE:
        return SysCallId::LOOKUP_DCOOKIE;
      case ARM64_SYSCALL::EVENTFD2:
        return SysCallId::EVENTFD2;
      case ARM64_SYSCALL::EPOLL_CREATE1:
        return SysCallId::EPOLL_CREATE1;
      case ARM64_SYSCALL::EPOLL_CTL:
        return SysCallId::EPOLL_CTL;
      case ARM64_SYSCALL::EPOLL_PWAIT:
        return SysCallId::EPOLL_PWAIT;
      case ARM64_SYSCALL::DUP:
        return SysCallId::DUP;
      case ARM64_SYSCALL::DUP3:
        return SysCallId::DUP3;
      case ARM64_SYSCALL::FCNTL:
        return SysCallId::FCNTL;
      case ARM64_SYSCALL::INOTIFY_INIT1:
        return SysCallId::INOTIFY_INIT1;
      case ARM64_SYSCALL::INOTIFY_ADD_WATCH:
        return SysCallId::INOTIFY_ADD_WATCH;
      case ARM64_SYSCALL::INOTIFY_RM_WATCH:
        return SysCallId::INOTIFY_RM_WATCH;
      case ARM64_SYSCALL::IOCTL:
        return SysCallId::IOCTL;
      case ARM64_SYSCALL::IOPRIO_SET:
        return SysCallId::IOPRIO_SET;
      case ARM64_SYSCALL::IOPRIO_GET:
        return SysCallId::IOPRIO_GET;
      case ARM64_SYSCALL::FLOCK:
        return SysCallId::FLOCK;
      case ARM64_SYSCALL::MKNODAT:
        return SysCallId::MKNODAT;
      case ARM64_SYSCALL::MKDIRAT:
        return SysCallId::MKDIRAT;
      case ARM64_SYSCALL::UNLINKAT:
        return SysCallId::UNLINKAT;
      case ARM64_SYSCALL::SYMLINKAT:
        return SysCallId::SYMLINKAT;
      case ARM64_SYSCALL::LINKAT:
        return SysCallId::LINKAT;
      case ARM64_SYSCALL::RENAMEAT:
        return SysCallId::RENAMEAT;
      case ARM64_SYSCALL::UMOUNT2:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::MOUNT:
        return SysCallId::MOUNT;
      case ARM64_SYSCALL::PIVOT_ROOT:
        return SysCallId::PIVOT_ROOT;
      case ARM64_SYSCALL::NFSSERVCTL:
        return SysCallId::NFSSERVCTL;
      case ARM64_SYSCALL::STATFS:
        return SysCallId::STATFS;
      case ARM64_SYSCALL::TRUNCATE:
        return SysCallId::TRUNCATE;
      case ARM64_SYSCALL::FTRUNCATE:
        return SysCallId::FTRUNCATE;
      case ARM64_SYSCALL::FALLOCATE:
        return SysCallId::FALLOCATE;
      case ARM64_SYSCALL::FACCESSAT:
        return SysCallId::FACCESSAT;
      case ARM64_SYSCALL::FCHDIR:
        return SysCallId::FCHDIR;
      case ARM64_SYSCALL::CHROOT:
        return SysCallId::CHROOT;
      case ARM64_SYSCALL::FCHMOD:
        return SysCallId::FCHMOD;
      case ARM64_SYSCALL::FCHMODAT:
        return SysCallId::FCHMODAT;
      case ARM64_SYSCALL::FCHOWNAT:
        return SysCallId::FCHOWNAT;
      case ARM64_SYSCALL::FCHOWN:
        return SysCallId::FCHOWN;
      case ARM64_SYSCALL::OPENAT:
        return SysCallId::OPENAT;
      case ARM64_SYSCALL::CLOSE:
        return SysCallId::CLOSE;
      case ARM64_SYSCALL::VHANGUP:
        return SysCallId::VHANGUP;
      case ARM64_SYSCALL::PIPE2:
        return SysCallId::PIPE2;
      case ARM64_SYSCALL::QUOTACTL:
        return SysCallId::QUOTACTL;
      case ARM64_SYSCALL::GETDENTS64:
        return SysCallId::GETDENTS64;
      case ARM64_SYSCALL::LSEEK:
        return SysCallId::LSEEK;
      case ARM64_SYSCALL::READ:
        return SysCallId::READ;
      case ARM64_SYSCALL::WRITE:
        return SysCallId::WRITE;
      case ARM64_SYSCALL::READV:
        return SysCallId::READV;
      case ARM64_SYSCALL::WRITEV:
        return SysCallId::WRITEV;
      case ARM64_SYSCALL::PREAD64:
        return SysCallId::PREAD64;
      case ARM64_SYSCALL::PWRITE64:
        return SysCallId::PWRITE64;
      case ARM64_SYSCALL::PREADV:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::PWRITEV:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SENDFILE:
        return SysCallId::SENDFILE;
      case ARM64_SYSCALL::PSELECT6:
        return SysCallId::PSELECT6;
      case ARM64_SYSCALL::PPOLL:
        return SysCallId::PPOLL;
      case ARM64_SYSCALL::SIGNALFD4:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::VMSPLICE:
        return SysCallId::VMSPLICE;
      case ARM64_SYSCALL::SPLICE:
        return SysCallId::SPLICE;
      case ARM64_SYSCALL::TEE:
        return SysCallId::TEE;
      case ARM64_SYSCALL::READLINKAT:
        return SysCallId::READLINKAT;
      case ARM64_SYSCALL::NEWFSTATAT:
        return SysCallId::NEWFSTATAT;
      case ARM64_SYSCALL::FSTAT:
        return SysCallId::FSTAT;
      case ARM64_SYSCALL::SYNC:
        return SysCallId::SYNC;
      case ARM64_SYSCALL::FSYNC:
        return SysCallId::FSYNC;
      case ARM64_SYSCALL::FDATASYNC:
        return SysCallId::FDATASYNC;
      case ARM64_SYSCALL::SYNC_FILE_RANGE:
        return SysCallId::SYNC_FILE_RANGE;
      case ARM64_SYSCALL::TIMERFD_CREATE:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::TIMERFD_SETTIME:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::TIMERFD_GETTIME:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::UTIMENSAT:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::ACCT:
        return SysCallId::ACCT;
      case ARM64_SYSCALL::CAPGET:
        return SysCallId::CAPGET;
      case ARM64_SYSCALL::CAPSET:
        return SysCallId::CAPSET;
      case ARM64_SYSCALL::PERSONALITY:
        return SysCallId::PERSONALITY;
      case ARM64_SYSCALL::EXIT:
        return SysCallId::EXIT;
      case ARM64_SYSCALL::EXIT_GROUP:
        return SysCallId::EXIT_GROUP;
      case ARM64_SYSCALL::WAITID:
        return SysCallId::WAITID;
      case ARM64_SYSCALL::SET_TID_ADDRESS:
        return SysCallId::SET_TID_ADDRESS;
      case ARM64_SYSCALL::UNSHARE:
        return SysCallId::UNSHARE;
      case ARM64_SYSCALL::FUTEX:
        return SysCallId::FUTEX;
      case ARM64_SYSCALL::SET_ROBUST_LIST:
        return SysCallId::SET_ROBUST_LIST;
      case ARM64_SYSCALL::GET_ROBUST_LIST:
        return SysCallId::GET_ROBUST_LIST;
      case ARM64_SYSCALL::NANOSLEEP:
        return SysCallId::NANOSLEEP;
      case ARM64_SYSCALL::GETITIMER:
        return SysCallId::GETITIMER;
      case ARM64_SYSCALL::SETITIMER:
        return SysCallId::SETITIMER;
      case ARM64_SYSCALL::KEXEC_LOAD:
        return SysCallId::KEXEC_LOAD;
      case ARM64_SYSCALL::INIT_MODULE:
        return SysCallId::INIT_MODULE;
      case ARM64_SYSCALL::DELETE_MODULE:
        return SysCallId::DELETE_MODULE;
      case ARM64_SYSCALL::TIMER_CREATE:
        return SysCallId::TIMER_CREATE;
      case ARM64_SYSCALL::TIMER_SETTIME:
        return SysCallId::TIMER_SETTIME;
      case ARM64_SYSCALL::TIMER_GETTIME:
        return SysCallId::TIMER_GETTIME;
      case ARM64_SYSCALL::TIMER_GETOVERRUN:
        return SysCallId::TIMER_GETOVERRUN;
      case ARM64_SYSCALL::TIMER_DELETE:
        return SysCallId::TIMER_DELETE;
      case ARM64_SYSCALL::CLOCK_SETTIME:
        return SysCallId::CLOCK_SETTIME;
      case ARM64_SYSCALL::CLOCK_GETTIME:
        return SysCallId::CLOCK_GETTIME;
      case ARM64_SYSCALL::CLOCK_GETRES:
        return SysCallId::CLOCK_GETRES;
      case ARM64_SYSCALL::CLOCK_NANOSLEEP:
        return SysCallId::CLOCK_NANOSLEEP;
      case ARM64_SYSCALL::SYSLOG:
        return SysCallId::SYSLOG;
      case ARM64_SYSCALL::PTRACE:
        return SysCallId::PTRACE;
      case ARM64_SYSCALL::SCHED_SETPARAM:
        return SysCallId::SCHED_SETPARAM;
      case ARM64_SYSCALL::SCHED_SETSCHEDULER:
        return SysCallId::SCHED_SETSCHEDULER;
      case ARM64_SYSCALL::SCHED_GETSCHEDULER:
        return SysCallId::SCHED_GETSCHEDULER;
      case ARM64_SYSCALL::SCHED_GETPARAM:
        return SysCallId::SCHED_GETPARAM;
      case ARM64_SYSCALL::SCHED_SETAFFINITY:
        return SysCallId::SCHED_SETAFFINITY;
      case ARM64_SYSCALL::SCHED_GETAFFINITY:
        return SysCallId::SCHED_GETAFFINITY;
      case ARM64_SYSCALL::SCHED_YIELD:
        return SysCallId::SCHED_YIELD;
      case ARM64_SYSCALL::SCHED_GET_PRIORITY_MAX:
        return SysCallId::SCHED_GET_PRIORITY_MAX;
      case ARM64_SYSCALL::SCHED_GET_PRIORITY_MIN:
        return SysCallId::SCHED_GET_PRIORITY_MIN;
      case ARM64_SYSCALL::SCHED_RR_GET_INTERVAL:
        return SysCallId::SCHED_RR_GET_INTERVAL;
      case ARM64_SYSCALL::KILL:
        return SysCallId::KILL;
      case ARM64_SYSCALL::TKILL:
        return SysCallId::TKILL;
      case ARM64_SYSCALL::TGKILL:
        return SysCallId::TGKILL;
      case ARM64_SYSCALL::SIGALTSTACK:
        return SysCallId::SIGALTSTACK;
      case ARM64_SYSCALL::RT_SIGSUSPEND:
        return SysCallId::RT_SIGSUSPEND;
      case ARM64_SYSCALL::RT_SIGACTION:
        return SysCallId::RT_SIGACTION;
      case ARM64_SYSCALL::RT_SIGPROCMASK:
        return SysCallId::RT_SIGPROCMASK;
      case ARM64_SYSCALL::RT_SIGPENDING:
        return SysCallId::RT_SIGPENDING;
      case ARM64_SYSCALL::RT_SIGTIMEDWAIT:
        return SysCallId::RT_SIGTIMEDWAIT;
      case ARM64_SYSCALL::RT_SIGQUEUEINFO:
        return SysCallId::RT_SIGQUEUEINFO;
      case ARM64_SYSCALL::RT_SIGRETURN:
        return SysCallId::RT_SIGRETURN;
      case ARM64_SYSCALL::SETPRIORITY:
        return SysCallId::SETPRIORITY;
      case ARM64_SYSCALL::GETPRIORITY:
        return SysCallId::GETPRIORITY;
      case ARM64_SYSCALL::REBOOT:
        return SysCallId::REBOOT;
      case ARM64_SYSCALL::SETREGID:
        return SysCallId::SETREGID;
      case ARM64_SYSCALL::SETGID:
        return SysCallId::SETGID;
      case ARM64_SYSCALL::SETREUID:
        return SysCallId::SETREUID;
      case ARM64_SYSCALL::SETUID:
        return SysCallId::SETUID;
      case ARM64_SYSCALL::SETRESUID:
        return SysCallId::SETRESUID;
      case ARM64_SYSCALL::GETRESUID:
        return SysCallId::GETRESUID;
      case ARM64_SYSCALL::SETRESGID:
        return SysCallId::SETRESGID;
      case ARM64_SYSCALL::GETRESGID:
        return SysCallId::GETRESGID;
      case ARM64_SYSCALL::SETFSUID:
        return SysCallId::SETFSUID;
      case ARM64_SYSCALL::SETFSGID:
        return SysCallId::SETFSGID;
      case ARM64_SYSCALL::TIMES:
        return SysCallId::TIMES;
      case ARM64_SYSCALL::SETPGID:
        return SysCallId::SETPGID;
      case ARM64_SYSCALL::GETPGID:
        return SysCallId::GETPGID;
      case ARM64_SYSCALL::GETSID:
        return SysCallId::GETSID;
      case ARM64_SYSCALL::SETSID:
        return SysCallId::SETSID;
      case ARM64_SYSCALL::GETGROUPS:
        return SysCallId::GETGROUPS;
      case ARM64_SYSCALL::SETGROUPS:
        return SysCallId::SETGROUPS;
      case ARM64_SYSCALL::UNAME:
        return SysCallId::UNAME;
      case ARM64_SYSCALL::SETHOSTNAME:
        return SysCallId::SETHOSTNAME;
      case ARM64_SYSCALL::SETDOMAINNAME:
        return SysCallId::SETDOMAINNAME;
      case ARM64_SYSCALL::GETRLIMIT:
        return SysCallId::GETRLIMIT;
      case ARM64_SYSCALL::SETRLIMIT:
        return SysCallId::SETRLIMIT;
      case ARM64_SYSCALL::GETRUSAGE:
        return SysCallId::GETRUSAGE;
      case ARM64_SYSCALL::UMASK:
        return SysCallId::UMASK;
      case ARM64_SYSCALL::PRCTL:
        return SysCallId::PRCTL;
      case ARM64_SYSCALL::GETCPU:
        return SysCallId::GETCPU;
      case ARM64_SYSCALL::GETTIMEOFDAY:
        return SysCallId::GETTIMEOFDAY;
      case ARM64_SYSCALL::SETTIMEOFDAY:
        return SysCallId::SETTIMEOFDAY;
      case ARM64_SYSCALL::ADJTIMEX:
        return SysCallId::ADJTIMEX;
      case ARM64_SYSCALL::GETPID:
        return SysCallId::GETPID;
      case ARM64_SYSCALL::GETPPID:
        return SysCallId::GETPPID;
      case ARM64_SYSCALL::GETUID:
        return SysCallId::GETUID;
      case ARM64_SYSCALL::GETEUID:
        return SysCallId::GETEUID;
      case ARM64_SYSCALL::GETGID:
        return SysCallId::GETGID;
      case ARM64_SYSCALL::GETEGID:
        return SysCallId::GETEGID;
      case ARM64_SYSCALL::GETTID:
        return SysCallId::GETTID;
      case ARM64_SYSCALL::SYSINFO:
        return SysCallId::SYSINFO;
      case ARM64_SYSCALL::MQ_OPEN:
        return SysCallId::MQ_OPEN;
      case ARM64_SYSCALL::MQ_UNLINK:
        return SysCallId::MQ_UNLINK;
      case ARM64_SYSCALL::MQ_TIMEDSEND:
        return SysCallId::MQ_TIMEDSEND;
      case ARM64_SYSCALL::MQ_TIMEDRECEIVE:
        return SysCallId::MQ_TIMEDRECEIVE;
      case ARM64_SYSCALL::MQ_NOTIFY:
        return SysCallId::MQ_NOTIFY;
      case ARM64_SYSCALL::MQ_GETSETATTR:
        return SysCallId::MQ_GETSETATTR;
      case ARM64_SYSCALL::MSGGET:
        return SysCallId::MSGGET;
      case ARM64_SYSCALL::MSGCTL:
        return SysCallId::MSGCTL;
      case ARM64_SYSCALL::MSGRCV:
        return SysCallId::MSGRCV;
      case ARM64_SYSCALL::MSGSND:
        return SysCallId::MSGSND;
      case ARM64_SYSCALL::SEMGET:
        return SysCallId::SEMGET;
      case ARM64_SYSCALL::SEMCTL:
        return SysCallId::SEMCTL;
      case ARM64_SYSCALL::SEMTIMEDOP:
        return SysCallId::SEMTIMEDOP;
      case ARM64_SYSCALL::SEMOP:
        return SysCallId::SEMOP;
      case ARM64_SYSCALL::SHMGET:
        return SysCallId::SHMGET;
      case ARM64_SYSCALL::SHMCTL:
        return SysCallId::SHMCTL;
      case ARM64_SYSCALL::SHMAT:
        return SysCallId::SHMAT;
      case ARM64_SYSCALL::SHMDT:
        return SysCallId::SHMDT;
      case ARM64_SYSCALL::SOCKET:
        return SysCallId::SOCKET;
      case ARM64_SYSCALL::SOCKETPAIR:
        return SysCallId::SOCKETPAIR;
      case ARM64_SYSCALL::BIND:
        return SysCallId::BIND;
      case ARM64_SYSCALL::LISTEN:
        return SysCallId::LISTEN;
      case ARM64_SYSCALL::ACCEPT:
        return SysCallId::ACCEPT;
      case ARM64_SYSCALL::CONNECT:
        return SysCallId::CONNECT;
      case ARM64_SYSCALL::GETSOCKNAME:
        return SysCallId::GETSOCKNAME;
      case ARM64_SYSCALL::GETPEERNAME:
        return SysCallId::GETPEERNAME;
      case ARM64_SYSCALL::SENDTO:
        return SysCallId::SENDTO;
      case ARM64_SYSCALL::RECVFROM:
        return SysCallId::RECVFROM;
      case ARM64_SYSCALL::SETSOCKOPT:
        return SysCallId::SETSOCKOPT;
      case ARM64_SYSCALL::GETSOCKOPT:
        return SysCallId::GETSOCKOPT;
      case ARM64_SYSCALL::SHUTDOWN:
        return SysCallId::SHUTDOWN;
      case ARM64_SYSCALL::SENDMSG:
        return SysCallId::SENDMSG;
      case ARM64_SYSCALL::RECVMSG:
        return SysCallId::RECVMSG;
      case ARM64_SYSCALL::READAHEAD:
        return SysCallId::READAHEAD;
      case ARM64_SYSCALL::BRK:
        return SysCallId::BRK;
      case ARM64_SYSCALL::MUNMAP:
        return SysCallId::MUNMAP;
      case ARM64_SYSCALL::MREMAP:
        return SysCallId::MREMAP;
      case ARM64_SYSCALL::ADD_KEY:
        return SysCallId::ADD_KEY;
      case ARM64_SYSCALL::REQUEST_KEY:
        return SysCallId::REQUEST_KEY;
      case ARM64_SYSCALL::KEYCTL:
        return SysCallId::KEYCTL;
      case ARM64_SYSCALL::CLONE:
        return SysCallId::CLONE;
      case ARM64_SYSCALL::EXECVE:
        return SysCallId::EXECVE;
      case ARM64_SYSCALL::MMAP:
        return SysCallId::MMAP2;
      case ARM64_SYSCALL::FADVISE64:
        return SysCallId::FADVISE64;
      case ARM64_SYSCALL::SWAPON:
        return SysCallId::SWAPON;
      case ARM64_SYSCALL::SWAPOFF:
        return SysCallId::SWAPOFF;
      case ARM64_SYSCALL::MPROTECT:
        return SysCallId::MPROTECT;
      case ARM64_SYSCALL::MSYNC:
        return SysCallId::MSYNC;
      case ARM64_SYSCALL::MLOCK:
        return SysCallId::MLOCK;
      case ARM64_SYSCALL::MUNLOCK:
        return SysCallId::MUNLOCK;
      case ARM64_SYSCALL::MLOCKALL:
        return SysCallId::MLOCKALL;
      case ARM64_SYSCALL::MUNLOCKALL:
        return SysCallId::MUNLOCKALL;
      case ARM64_SYSCALL::MINCORE:
        return SysCallId::MINCORE;
      case ARM64_SYSCALL::MADVISE:
        return SysCallId::MADVISE;
      case ARM64_SYSCALL::REMAP_FILE_PAGES:
        return SysCallId::REMAP_FILE_PAGES;
      case ARM64_SYSCALL::MBIND:
        return SysCallId::MBIND;
      case ARM64_SYSCALL::GET_MEMPOLICY:
        return SysCallId::GET_MEMPOLICY;
      case ARM64_SYSCALL::SET_MEMPOLICY:
        return SysCallId::SET_MEMPOLICY;
      case ARM64_SYSCALL::MIGRATE_PAGES:
        return SysCallId::MIGRATE_PAGES;
      case ARM64_SYSCALL::MOVE_PAGES:
        return SysCallId::MOVE_PAGES;
      case ARM64_SYSCALL::RT_TGSIGQUEUEINFO:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::PERF_EVENT_OPEN:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::ACCEPT4:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::RECVMMSG:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::WAIT4:
        return SysCallId::WAIT4;
      case ARM64_SYSCALL::PRLIMIT64:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::FANOTIFY_INIT:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::FANOTIFY_MARK:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::NAME_TO_HANDLE_AT:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::OPEN_BY_HANDLE_AT:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::CLOCK_ADJTIME:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SYNCFS:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SETNS:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SENDMMSG:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::PROCESS_VM_READV:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::PROCESS_VM_WRITEV:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::KCMP:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::FINIT_MODULE:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SCHED_SETATTR:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::SCHED_GETATTR:
        return SysCallId::NO_SYSCALL;
      case ARM64_SYSCALL::GETRANDOM:
        return SysCallId::GETRANDOM;
    default:
      return SysCallId::NO_SYSCALL;
    }
}

