export CXX_COMPILER=/home/hussain/pdev/linux-exp/src/buildroot/output/host/bin/arm-buildroot-linux-gnueabi-g++
export CC_COMPILER=/home/hussain/pdev/linux-exp/src/buildroot/output/host/bin/arm-buildroot-linux-gnueabi-gcc

cmake -S. -B build_arm -D CMAKE_C_COMPILER=$CC_COMPILER -D CMAKE_CXX_COMPILER=$CXX_COMPILER -DCAPSTONE_ARM64_SUPPORT=0 -DCAPSTONE_M68K_SUPPORT=0 -DCAPSTONE_SPARC_SUPPORT=0 -DCAPSTONE_SYSZ_SUPPORT=0 -DCAPSTONE_XCORE_SUPPORT=0 -DCAPSTONE_TMS320C64X_SUPPORT=0 -DCAPSTONE_M680X_SUPPORT=0 -DCAPSTONE_EVM_SUPPORT=0 -DCAPSTONE_MOS65XX_SUPPORT=0 -DCAPSTONE_WASM_SUPPORT=0 -DCAPSTONE_BPF_SUPPORT=0 -DCAPSTONE_RISCV_SUPPORT=0 -DCAPSTONE_SH_SUPPORT=0 -DCAPSTONE_TRICORE_SUPPORT=0 -DCAPSTONE_ARM_SUPPORT=1 -DCAPSTONE_X86_SUPPORT=0 -DCAPSTONE_MIPS_SUPPORT=0 -DCAPSTONE_PPC_SUPPORT=0

cmake --build build_arm --target shaman --target test_prog --target oop_test
