#include <iostream>

enum AMD64_SYSCALL : int16_t {
    IO_SETUP = 0,
    IO_DESTROY = 1,
    IO_SUBMIT = 2,
    IO_CANCEL = 3,
    IO_GETEVENTS = 4,
    SETXATTR = 5,
    LSETXATTR = 6,
    FSETXATTR = 7,
    GETXATTR = 8,
    LGETXATTR = 9,
    FGETXATTR = 10,
    LISTXATTR = 11,
    LLISTXATTR = 12,
    FLISTXATTR = 13,
    REMOVEXATTR = 14,
    LREMOVEXATTR = 15,
    FREMOVEXATTR = 16,
    GETCWD = 17,
    LOOKUP_DCOOKIE = 18,
    EVENTFD2 = 19,
    EPOLL_CREATE1 = 20,
    EPOLL_CTL = 21,
    EPOLL_PWAIT = 22,
    DUP = 23,
    DUP3 = 24,
    FCNTL = 25,
    INOTIFY_INIT1 = 26,
    INOTIFY_ADD_WATCH = 27,
    INOTIFY_RM_WATCH = 28,
    IOCTL = 29,
    IOPRIO_SET = 30,
    IOPRIO_GET = 31,
    FLOCK = 32,
    MKNODAT = 33,
    MKDIRAT = 34,
    UNLINKAT = 35,
    SYMLINKAT = 36,
    LINKAT = 37,
    RENAMEAT = 38,
    UMOUNT2 = 39,
    MOUNT = 40,
    PIVOT_ROOT = 41,
    NFSSERVCTL = 42,
    STATFS = 43,
    FSTATFS = 44,
    TRUNCATE = 45,
    FTRUNCATE = 46,
    FALLOCATE = 47,
    FACCESSAT = 48,
    CHDIR = 49,
    FCHDIR = 50,
    CHROOT = 51,
    FCHMOD = 52,
    FCHMODAT = 53,
    FCHOWNAT = 54,
    FCHOWN = 55,
    OPENAT = 56,
    CLOSE = 57,
    VHANGUP = 58,
    PIPE2 = 59,
    QUOTACTL = 60,
    GETDENTS64 = 61,
    LSEEK = 62,
    READ = 63,
    WRITE = 64,
    READV = 65,
    WRITEV = 66,
    PREAD64 = 67,
    PWRITE64 = 68,
    PREADV = 69,
    PWRITEV = 70,
    SENDFILE = 71,
    PSELECT6 = 72,
    PPOLL = 73,
    SIGNALFD4 = 74,
    VMSPLICE = 75,
    SPLICE = 76,
    TEE = 77,
    READLINKAT = 78,
    NEWFSTATAT = 79,
    FSTAT = 80,
    SYNC = 81,
    FSYNC = 82,
    FDATASYNC = 83,
    SYNC_FILE_RANGE2 = 84,
    SYNC_FILE_RANGE = 84,
    TIMERFD_CREATE = 85,
    TIMERFD_SETTIME = 86,
    TIMERFD_GETTIME = 87,
    UTIMENSAT = 88,
    ACCT = 89,
    CAPGET = 90,
    CAPSET = 91,
    PERSONALITY = 92,
    EXIT = 93,
    EXIT_GROUP = 94,
    WAITID = 95,
    SET_TID_ADDRESS = 96,
    UNSHARE = 97,
    FUTEX = 98,
    SET_ROBUST_LIST = 99,
    GET_ROBUST_LIST = 100,
    NANOSLEEP = 101,
    GETITIMER = 102,
    SETITIMER = 103,
    KEXEC_LOAD = 104,
    INIT_MODULE = 105,
    DELETE_MODULE = 106,
    TIMER_CREATE = 107,
    TIMER_GETTIME = 108,
    TIMER_GETOVERRUN = 109,
    TIMER_SETTIME = 110,
    TIMER_DELETE = 111,
    CLOCK_SETTIME = 112,
    CLOCK_GETTIME = 113,
    CLOCK_GETRES = 114,
    CLOCK_NANOSLEEP = 115,
    SYSLOG = 116,
    PTRACE = 117,
    SCHED_SETPARAM = 118,
    SCHED_SETSCHEDULER = 119,
    SCHED_GETSCHEDULER = 120,
    SCHED_GETPARAM = 121,
    SCHED_SETAFFINITY = 122,
    SCHED_GETAFFINITY = 123,
    SCHED_YIELD = 124,
    SCHED_GET_PRIORITY_MAX = 125,
    SCHED_GET_PRIORITY_MIN = 126,
    SCHED_RR_GET_INTERVAL = 127,
    KILL = 129,
    TKILL = 130,
    TGKILL = 131,
    SIGALTSTACK = 132,
    RT_SIGSUSPEND = 133,
    RT_SIGACTION = 134,
    RT_SIGPROCMASK = 135,
    RT_SIGPENDING = 136,
    RT_SIGTIMEDWAIT = 137,
    RT_SIGQUEUEINFO = 138,
    RT_SIGRETURN = 139,
    SETPRIORITY = 140,
    GETPRIORITY = 141,
    REBOOT = 142,
    SETREGID = 143,
    SETGID = 144,
    SETREUID = 145,
    SETUID = 146,
    SETRESUID = 147,
    GETRESUID = 148,
    SETRESGID = 149,
    GETRESGID = 150,
    SETFSUID = 151,
    SETFSGID = 152,
    TIMES = 153,
    SETPGID = 154,
    GETPGID = 155,
    GETSID = 156,
    SETSID = 157,
    GETGROUPS = 158,
    SETGROUPS = 159,
    UNAME = 160,
    SETHOSTNAME = 161,
    SETDOMAINNAME = 162,
    GETRLIMIT = 163,
    SETRLIMIT = 164,
    GETRUSAGE = 165,
    UMASK = 166,
    PRCTL = 167,
    GETCPU = 168,
    GETTIMEOFDAY = 169,
    SETTIMEOFDAY = 170,
    ADJTIMEX = 171,
    GETPID = 172,
    GETPPID = 173,
    GETUID = 174,
    GETEUID = 175,
    GETGID = 176,
    GETEGID = 177,
    GETTID = 178,
    SYSINFO = 179,
    MQ_OPEN = 180,
    MQ_UNLINK = 181,
    MQ_TIMEDSEND = 182,
    MQ_TIMEDRECEIVE = 183,
    MQ_NOTIFY = 184,
    MQ_GETSETATTR = 185,
    MSGGET = 186,
    MSGCTL = 187,
    MSGRCV = 188,
    MSGSND = 189,
    SEMGET = 190,
    SEMCTL = 191,
    SEMTIMEDOP = 192,
    SEMOP = 193,
    SHMGET = 194,
    SHMCTL = 195,
    SHMAT = 196,
    SHMDT = 197,
    SOCKET = 198,
    SOCKETPAIR = 199,
    BIND = 200,
    LISTEN = 201,
    ACCEPT = 202,
    CONNECT = 203,
    GETSOCKNAME = 204,
    GETPEERNAME = 205,
    SENDTO = 206,
    RECVFROM = 207,
    SETSOCKOPT = 208,
    GETSOCKOPT = 209,
    SHUTDOWN = 210,
    SENDMSG = 211,
    RECVMSG = 212,
    READAHEAD = 213,
    BRK = 214,
    MUNMAP = 215,
    MREMAP = 216,
    ADD_KEY = 217,
    REQUEST_KEY = 218,
    KEYCTL = 219,
    CLONE = 220,
    EXECVE = 221,
    MMAP = 222,
    FADVISE64 = 223,
    SWAPON = 224,
    SWAPOFF = 225,
    MPROTECT = 226,
    MSYNC = 227,
    MLOCK = 228,
    MUNLOCK = 229,
    MLOCKALL = 230,
    MUNLOCKALL = 231,
    MINCORE = 232,
    MADVISE = 233,
    REMAP_FILE_PAGES = 234,
    MBIND = 235,
    GET_MEMPOLICY = 236,
    SET_MEMPOLICY = 237,
    MIGRATE_PAGES = 238,
    MOVE_PAGES = 239,
    RT_TGSIGQUEUEINFO = 240,
    PERF_EVENT_OPEN = 241,
    ACCEPT4 = 242,
    RECVMMSG = 243,
    WAIT4 = 260,
    PRLIMIT64 = 261,
    FANOTIFY_INIT = 262,
    FANOTIFY_MARK = 263,
    NAME_TO_HANDLE_AT = 264,
    OPEN_BY_HANDLE_AT = 265,
    CLOCK_ADJTIME = 266,
    SYNCFS = 267,
    SETNS = 268,
    SENDMMSG = 269,
    PROCESS_VM_READV = 270,
    PROCESS_VM_WRITEV = 271,
    KCMP = 272,
    FINIT_MODULE = 273,
    SCHED_SETATTR = 274,
    SCHED_GETATTR = 275,
    GETRANDOM = 278
};


#define SYSCALL_MAPSYSCALL) case AMD64_SYSCALL::##SYSCALL: \
  return SysCallId::##SYSCALL;

#define UNSUPPORTED_SYSCALL_MAPSYSCALL) case aarch64_sys_##SYSCALL: \
  return SysCallId::NO_SYSCALL;


static SysCallId amd64_canonicalize_syscall (AMD64_SYSCALL syscall_number)
{
    switch (syscall_number)
    {
      SYSCALL_MAP(IO_SETUP);
      SYSCALL_MAP(IO_DESTROY);
      SYSCALL_MAP(IO_SUBMIT);
      SYSCALL_MAP(IO_CANCEL);
      SYSCALL_MAP(IO_GETEVENTS);
      SYSCALL_MAP(SETXATTR);
      SYSCALL_MAP(LSETXATTR);
      SYSCALL_MAP(FSETXATTR);
      SYSCALL_MAP(GETXATTR);
      SYSCALL_MAP(LGETXATTR);
      SYSCALL_MAP(FGETXATTR);
      SYSCALL_MAP(LISTXATTR);
      SYSCALL_MAP(LLISTXATTR);
      SYSCALL_MAP(FLISTXATTR);
      SYSCALL_MAP(REMOVEXATTR);
      SYSCALL_MAP(LREMOVEXATTR);
      SYSCALL_MAP(FREMOVEXATTR);
      SYSCALL_MAP(GETCWD);
      SYSCALL_MAP(LOOKUP_DCOOKIE);
      SYSCALL_MAP(EVENTFD2);
      SYSCALL_MAP(EPOLL_CREATE1);
      SYSCALL_MAP(EPOLL_CTL);
      SYSCALL_MAP(EPOLL_PWAIT);
      SYSCALL_MAP(DUP);
      SYSCALL_MAP(DUP3);
      SYSCALL_MAP(FCNTL);
      SYSCALL_MAP(INOTIFY_INIT1);
      SYSCALL_MAP(INOTIFY_ADD_WATCH);
      SYSCALL_MAP(INOTIFY_RM_WATCH);
      SYSCALL_MAP(IOCTL);
      SYSCALL_MAP(IOPRIO_SET);
      SYSCALL_MAP(IOPRIO_GET);
      SYSCALL_MAP(FLOCK);
      SYSCALL_MAP(MKNODAT);
      SYSCALL_MAP(MKDIRAT);
      SYSCALL_MAP(UNLINKAT);
      SYSCALL_MAP(SYMLINKAT);
      SYSCALL_MAP(LINKAT);
      SYSCALL_MAP(RENAMEAT);
      UNSUPPORTED_SYSCALL_MAP(UMOUNT2);
      SYSCALL_MAP(MOUNT);
      SYSCALL_MAP(PIVOT_ROOT);
      SYSCALL_MAP(NFSSERVCTL);
      SYSCALL_MAP(STATFS);
      SYSCALL_MAP(TRUNCATE);
      SYSCALL_MAP(FTRUNCATE);
      SYSCALL_MAP(FALLOCATE);
      SYSCALL_MAP(FACCESSAT);
      SYSCALL_MAP(FCHDIR);
      SYSCALL_MAP(CHROOT);
      SYSCALL_MAP(FCHMOD);
      SYSCALL_MAP(FCHMODAT);
      SYSCALL_MAP(FCHOWNAT);
      SYSCALL_MAP(FCHOWN);
      SYSCALL_MAP(OPENAT);
      SYSCALL_MAP(CLOSE);
      SYSCALL_MAP(VHANGUP);
      SYSCALL_MAP(PIPE2);
      SYSCALL_MAP(QUOTACTL);
      SYSCALL_MAP(GETDENTS64);
      SYSCALL_MAP(LSEEK);
      SYSCALL_MAP(READ);
      SYSCALL_MAP(WRITE);
      SYSCALL_MAP(READV);
      SYSCALL_MAP(WRITEV);
      SYSCALL_MAP(PREAD64);
      SYSCALL_MAP(PWRITE64);
      UNSUPPORTED_SYSCALL_MAP(PREADV);
      UNSUPPORTED_SYSCALL_MAP(PWRITEV);
      SYSCALL_MAP(SENDFILE);
      SYSCALL_MAP(PSELECT6);
      SYSCALL_MAP(PPOLL);
      UNSUPPORTED_SYSCALL_MAP(SIGNALFD4);
      SYSCALL_MAP(VMSPLICE);
      SYSCALL_MAP(SPLICE);
      SYSCALL_MAP(TEE);
      SYSCALL_MAP(READLINKAT);
      SYSCALL_MAP(NEWFSTATAT);
      SYSCALL_MAP(FSTAT);
      SYSCALL_MAP(SYNC);
      SYSCALL_MAP(FSYNC);
      SYSCALL_MAP(FDATASYNC);
      SYSCALL_MAP(SYNC_FILE_RANGE);
      UNSUPPORTED_SYSCALL_MAP(TIMERFD_CREATE);
      UNSUPPORTED_SYSCALL_MAP(TIMERFD_SETTIME);
      UNSUPPORTED_SYSCALL_MAP(TIMERFD_GETTIME);
      UNSUPPORTED_SYSCALL_MAP(UTIMENSAT);
      SYSCALL_MAP(ACCT);
      SYSCALL_MAP(CAPGET);
      SYSCALL_MAP(CAPSET);
      SYSCALL_MAP(PERSONALITY);
      SYSCALL_MAP(EXIT);
      SYSCALL_MAP(EXIT_GROUP);
      SYSCALL_MAP(WAITID);
      SYSCALL_MAP(SET_TID_ADDRESS);
      SYSCALL_MAP(UNSHARE);
      SYSCALL_MAP(FUTEX);
      SYSCALL_MAP(SET_ROBUST_LIST);
      SYSCALL_MAP(GET_ROBUST_LIST);
      SYSCALL_MAP(NANOSLEEP);
      SYSCALL_MAP(GETITIMER);
      SYSCALL_MAP(SETITIMER);
      SYSCALL_MAP(KEXEC_LOAD);
      SYSCALL_MAP(INIT_MODULE);
      SYSCALL_MAP(DELETE_MODULE);
      SYSCALL_MAP(TIMER_CREATE);
      SYSCALL_MAP(TIMER_SETTIME);
      SYSCALL_MAP(TIMER_GETTIME);
      SYSCALL_MAP(TIMER_GETOVERRUN);
      SYSCALL_MAP(TIMER_DELETE);
      SYSCALL_MAP(CLOCK_SETTIME);
      SYSCALL_MAP(CLOCK_GETTIME);
      SYSCALL_MAP(CLOCK_GETRES);
      SYSCALL_MAP(CLOCK_NANOSLEEP);
      SYSCALL_MAP(SYSLOG);
      SYSCALL_MAP(PTRACE);
      SYSCALL_MAP(SCHED_SETPARAM);
      SYSCALL_MAP(SCHED_SETSCHEDULER);
      SYSCALL_MAP(SCHED_GETSCHEDULER);
      SYSCALL_MAP(SCHED_GETPARAM);
      SYSCALL_MAP(SCHED_SETAFFINITY);
      SYSCALL_MAP(SCHED_GETAFFINITY);
      SYSCALL_MAP(SCHED_YIELD);
      SYSCALL_MAP(SCHED_GET_PRIORITY_MAX);
      SYSCALL_MAP(SCHED_GET_PRIORITY_MIN);
      SYSCALL_MAP(SCHED_RR_GET_INTERVAL);
      SYSCALL_MAP(KILL);
      SYSCALL_MAP(TKILL);
      SYSCALL_MAP(TGKILL);
      SYSCALL_MAP(SIGALTSTACK);
      SYSCALL_MAP(RT_SIGSUSPEND);
      SYSCALL_MAP(RT_SIGACTION);
      SYSCALL_MAP(RT_SIGPROCMASK);
      SYSCALL_MAP(RT_SIGPENDING);
      SYSCALL_MAP(RT_SIGTIMEDWAIT);
      SYSCALL_MAP(RT_SIGQUEUEINFO);
      SYSCALL_MAP(RT_SIGRETURN);
      SYSCALL_MAP(SETPRIORITY);
      SYSCALL_MAP(GETPRIORITY);
      SYSCALL_MAP(REBOOT);
      SYSCALL_MAP(SETREGID);
      SYSCALL_MAP(SETGID);
      SYSCALL_MAP(SETREUID);
      SYSCALL_MAP(SETUID);
      SYSCALL_MAP(SETRESUID);
      SYSCALL_MAP(GETRESUID);
      SYSCALL_MAP(SETRESGID);
      SYSCALL_MAP(GETRESGID);
      SYSCALL_MAP(SETFSUID);
      SYSCALL_MAP(SETFSGID);
      SYSCALL_MAP(TIMES);
      SYSCALL_MAP(SETPGID);
      SYSCALL_MAP(GETPGID);
      SYSCALL_MAP(GETSID);
      SYSCALL_MAP(SETSID);
      SYSCALL_MAP(GETGROUPS);
      SYSCALL_MAP(SETGROUPS);
      SYSCALL_MAP(UNAME);
      SYSCALL_MAP(SETHOSTNAME);
      SYSCALL_MAP(SETDOMAINNAME);
      SYSCALL_MAP(GETRLIMIT);
      SYSCALL_MAP(SETRLIMIT);
      SYSCALL_MAP(GETRUSAGE);
      SYSCALL_MAP(UMASK);
      SYSCALL_MAP(PRCTL);
      SYSCALL_MAP(GETCPU);
      SYSCALL_MAP(GETTIMEOFDAY);
      SYSCALL_MAP(SETTIMEOFDAY);
      SYSCALL_MAP(ADJTIMEX);
      SYSCALL_MAP(GETPID);
      SYSCALL_MAP(GETPPID);
      SYSCALL_MAP(GETUID);
      SYSCALL_MAP(GETEUID);
      SYSCALL_MAP(GETGID);
      SYSCALL_MAP(GETEGID);
      SYSCALL_MAP(GETTID);
      SYSCALL_MAP(SYSINFO);
      SYSCALL_MAP(MQ_OPEN);
      SYSCALL_MAP(MQ_UNLINK);
      SYSCALL_MAP(MQ_TIMEDSEND);
      SYSCALL_MAP(MQ_TIMEDRECEIVE);
      SYSCALL_MAP(MQ_NOTIFY);
      SYSCALL_MAP(MQ_GETSETATTR);
      SYSCALL_MAP(MSGGET);
      SYSCALL_MAP(MSGCTL);
      SYSCALL_MAP(MSGRCV);
      SYSCALL_MAP(MSGSND);
      SYSCALL_MAP(SEMGET);
      SYSCALL_MAP(SEMCTL);
      SYSCALL_MAP(SEMTIMEDOP);
      SYSCALL_MAP(SEMOP);
      SYSCALL_MAP(SHMGET);
      SYSCALL_MAP(SHMCTL);
      SYSCALL_MAP(SHMAT);
      SYSCALL_MAP(SHMDT);
      SYSCALL_MAP(SOCKET);
      SYSCALL_MAP(SOCKETPAIR);
      SYSCALL_MAP(BIND);
      SYSCALL_MAP(LISTEN);
      SYSCALL_MAP(ACCEPT);
      SYSCALL_MAP(CONNECT);
      SYSCALL_MAP(GETSOCKNAME);
      SYSCALL_MAP(GETPEERNAME);
      SYSCALL_MAP(SENDTO);
      SYSCALL_MAP(RECVFROM);
      SYSCALL_MAP(SETSOCKOPT);
      SYSCALL_MAP(GETSOCKOPT);
      SYSCALL_MAP(SHUTDOWN);
      SYSCALL_MAP(SENDMSG);
      SYSCALL_MAP(RECVMSG);
      SYSCALL_MAP(READAHEAD);
      SYSCALL_MAP(BRK);
      SYSCALL_MAP(MUNMAP);
      SYSCALL_MAP(MREMAP);
      SYSCALL_MAP(ADD_KEY);
      SYSCALL_MAP(REQUEST_KEY);
      SYSCALL_MAP(KEYCTL);
      SYSCALL_MAP(CLONE);
      SYSCALL_MAP(EXECVE);
      case AMD64_SYSCALL::MMAP:
        return SyscallId::MMAP2;
      SYSCALL_MAP(FADVISE64);
      SYSCALL_MAP(SWAPON);
      SYSCALL_MAP(SWAPOFF);
      SYSCALL_MAP(MPROTECT);
      SYSCALL_MAP(MSYNC);
      SYSCALL_MAP(MLOCK);
      SYSCALL_MAP(MUNLOCK);
      SYSCALL_MAP(MLOCKALL);
      SYSCALL_MAP(MUNLOCKALL);
      SYSCALL_MAP(MINCORE);
      SYSCALL_MAP(MADVISE);
      SYSCALL_MAP(REMAP_FILE_PAGES);
      SYSCALL_MAP(MBIND);
      SYSCALL_MAP(GET_MEMPOLICY);
      SYSCALL_MAP(SET_MEMPOLICY);
      SYSCALL_MAP(MIGRATE_PAGES);
      SYSCALL_MAP(MOVE_PAGES);
      UNSUPPORTED_SYSCALL_MAP(RT_TGSIGQUEUEINFO);
      UNSUPPORTED_SYSCALL_MAP(PERF_EVENT_OPEN);
      UNSUPPORTED_SYSCALL_MAP(ACCEPT4);
      UNSUPPORTED_SYSCALL_MAP(RECVMMSG);
      SYSCALL_MAP(WAIT4);
      UNSUPPORTED_SYSCALL_MAP(PRLIMIT64);
      UNSUPPORTED_SYSCALL_MAP(FANOTIFY_INIT);
      UNSUPPORTED_SYSCALL_MAP(FANOTIFY_MARK);
      UNSUPPORTED_SYSCALL_MAP(NAME_TO_HANDLE_AT);
      UNSUPPORTED_SYSCALL_MAP(OPEN_BY_HANDLE_AT);
      UNSUPPORTED_SYSCALL_MAP(CLOCK_ADJTIME);
      UNSUPPORTED_SYSCALL_MAP(SYNCFS);
      UNSUPPORTED_SYSCALL_MAP(SETNS);
      UNSUPPORTED_SYSCALL_MAP(SENDMMSG);
      UNSUPPORTED_SYSCALL_MAP(PROCESS_VM_READV);
      UNSUPPORTED_SYSCALL_MAP(PROCESS_VM_WRITEV);
      UNSUPPORTED_SYSCALL_MAP(KCMP);
      UNSUPPORTED_SYSCALL_MAP(FINIT_MODULE);
      UNSUPPORTED_SYSCALL_MAP(SCHED_SETATTR);
      UNSUPPORTED_SYSCALL_MAP(SCHED_GETATTR);
      SYSCALL_MAP(GETRANDOM);
  default:
    return gdb_sys_no_syscall;
    }
}