#include "syscall.hpp"


SysCallId amd64_canonicalize_syscall(AMD64_SYSCALL syscall_number)
{

  switch (syscall_number) {
  case AMD64_SYSCALL::READ:
  // case AMD64_X32_SYSCALL::READ:
    return SysCallId::READ;

  case AMD64_SYSCALL::WRITE:
  // case AMD64_X32_SYSCALL::WRITE:
    return SysCallId::WRITE;

  case AMD64_SYSCALL::OPEN:
  // case AMD64_X32_SYSCALL::OPEN:
    return SysCallId::OPEN;

  case AMD64_SYSCALL::CLOSE:
  // case AMD64_X32_SYSCALL::CLOSE:
    return SysCallId::CLOSE;

  case AMD64_SYSCALL::NEWSTAT:
  // case AMD64_X32_SYSCALL::NEWSTAT:
    return SysCallId::NEWSTAT;

  case AMD64_SYSCALL::NEWFSTAT:
  // case AMD64_X32_SYSCALL::NEWFSTAT:
    return SysCallId::NEWFSTAT;

  case AMD64_SYSCALL::NEWLSTAT:
  // case AMD64_X32_SYSCALL::NEWLSTAT:
    return SysCallId::NEWLSTAT;

  case AMD64_SYSCALL::POLL:
  // case AMD64_X32_SYSCALL::POLL:
    return SysCallId::POLL;

  case AMD64_SYSCALL::LSEEK:
  // case AMD64_X32_SYSCALL::LSEEK:
    return SysCallId::LSEEK;

  case AMD64_SYSCALL::MMAP:
  // case AMD64_X32_SYSCALL::MMAP:
    return SysCallId::MMAP2;

  case AMD64_SYSCALL::MPROTECT:
  // case AMD64_X32_SYSCALL::MPROTECT:
    return SysCallId::MPROTECT;

  case AMD64_SYSCALL::MUNMAP:
  // case AMD64_X32_SYSCALL::MUNMAP:
    return SysCallId::MUNMAP;

  case AMD64_SYSCALL::BRK:
  // case AMD64_X32_SYSCALL::BRK:
    return SysCallId::BRK;

  case AMD64_SYSCALL::RT_SIGACTION:
  // case AMD64_X32_SYSCALL::RT_SIGACTION:
    return SysCallId::RT_SIGACTION;

  case AMD64_SYSCALL::RT_SIGPROCMASK:
  // case AMD64_X32_SYSCALL::RT_SIGPROCMASK:
    return SysCallId::RT_SIGPROCMASK;

  case AMD64_SYSCALL::RT_SIGRETURN:
  // case AMD64_X32_SYSCALL::RT_SIGRETURN:
    return SysCallId::RT_SIGRETURN;

  case AMD64_SYSCALL::IOCTL:
  // case AMD64_X32_SYSCALL::IOCTL:
    return SysCallId::IOCTL;

  case AMD64_SYSCALL::PREAD64:
  // case AMD64_X32_SYSCALL::PREAD64:
    return SysCallId::PREAD64;

  case AMD64_SYSCALL::PWRITE64:
  // case AMD64_X32_SYSCALL::PWRITE64:
    return SysCallId::PWRITE64;

  case AMD64_SYSCALL::READV:
  // case AMD64_X32_SYSCALL::READV:
    return SysCallId::READV;

  case AMD64_SYSCALL::WRITEV:
  // case AMD64_X32_SYSCALL::WRITEV:
    return SysCallId::WRITEV;

  case AMD64_SYSCALL::ACCESS:
  // case AMD64_X32_SYSCALL::ACCESS:
    return SysCallId::ACCESS;

  case AMD64_SYSCALL::PIPE:
  // case AMD64_X32_SYSCALL::PIPE:
    return SysCallId::PIPE;

  case AMD64_SYSCALL::PIPE2:
    return SysCallId::PIPE;

  case AMD64_SYSCALL::GETRANDOM:
    return SysCallId::GETRANDOM;

  case AMD64_SYSCALL::SELECT:
  // case AMD64_X32_SYSCALL::SELECT:
    return SysCallId::SELECT;

  case AMD64_SYSCALL::SCHED_YIELD:
  // case AMD64_X32_SYSCALL::SCHED_YIELD:
    return SysCallId::SCHED_YIELD;

  case AMD64_SYSCALL::MREMAP:
  // case AMD64_X32_SYSCALL::MREMAP:
    return SysCallId::MREMAP;

  case AMD64_SYSCALL::MSYNC:
  // case AMD64_X32_SYSCALL::MSYNC:
    return SysCallId::MSYNC;

  case AMD64_SYSCALL::MINCORE:
  // case AMD64_X32_SYSCALL::MINCORE:
    return SysCallId::MINCORE;

  case AMD64_SYSCALL::MADVISE:
  // case AMD64_X32_SYSCALL::MADVISE:
    return SysCallId::MADVISE;

  case AMD64_SYSCALL::SHMGET:
  // case AMD64_X32_SYSCALL::SHMGET:
    return SysCallId::SHMGET;

  case AMD64_SYSCALL::SHMAT:
  // case AMD64_X32_SYSCALL::SHMAT:
    return SysCallId::SHMAT;

  case AMD64_SYSCALL::SHMCTL:
  // case AMD64_X32_SYSCALL::SHMCTL:
    return SysCallId::SHMCTL;

  case AMD64_SYSCALL::DUP:
  // case AMD64_X32_SYSCALL::DUP:
    return SysCallId::DUP;

  case AMD64_SYSCALL::DUP2:
  // case AMD64_X32_SYSCALL::DUP2:
    return SysCallId::DUP2;

  case AMD64_SYSCALL::PAUSE:
  // case AMD64_X32_SYSCALL::PAUSE:
    return SysCallId::PAUSE;

  case AMD64_SYSCALL::NANOSLEEP:
  // case AMD64_X32_SYSCALL::NANOSLEEP:
    return SysCallId::NANOSLEEP;

  case AMD64_SYSCALL::GETITIMER:
  // case AMD64_X32_SYSCALL::GETITIMER:
    return SysCallId::GETITIMER;

  case AMD64_SYSCALL::ALARM:
  // case AMD64_X32_SYSCALL::ALARM:
    return SysCallId::ALARM;

  case AMD64_SYSCALL::SETITIMER:
  // case AMD64_X32_SYSCALL::SETITIMER:
    return SysCallId::SETITIMER;

  case AMD64_SYSCALL::GETPID:
  // case AMD64_X32_SYSCALL::GETPID:
    return SysCallId::GETPID;

  case AMD64_SYSCALL::SENDFILE64:
  // case AMD64_X32_SYSCALL::SENDFILE64:
    return SysCallId::SENDFILE64;

  case AMD64_SYSCALL::SOCKET:
  // case AMD64_X32_SYSCALL::SOCKET:
    return SysCallId::SOCKET;

  case AMD64_SYSCALL::CONNECT:
  // case AMD64_X32_SYSCALL::CONNECT:
    return SysCallId::CONNECT;

  case AMD64_SYSCALL::ACCEPT:
  // case AMD64_X32_SYSCALL::ACCEPT:
    return SysCallId::ACCEPT;

  case AMD64_SYSCALL::SENDTO:
  // case AMD64_X32_SYSCALL::SENDTO:
    return SysCallId::SENDTO;

  case AMD64_SYSCALL::RECVFROM:
  // case AMD64_X32_SYSCALL::RECVFROM:
    return SysCallId::RECVFROM;

  case AMD64_SYSCALL::SENDMSG:
  // case AMD64_X32_SYSCALL::SENDMSG:
    return SysCallId::SENDMSG;

  case AMD64_SYSCALL::RECVMSG:
  // case AMD64_X32_SYSCALL::RECVMSG:
    return SysCallId::RECVMSG;

  case AMD64_SYSCALL::SHUTDOWN:
  // case AMD64_X32_SYSCALL::SHUTDOWN:
    return SysCallId::SHUTDOWN;

  case AMD64_SYSCALL::BIND:
  // case AMD64_X32_SYSCALL::BIND:
    return SysCallId::BIND;

  case AMD64_SYSCALL::LISTEN:
  // case AMD64_X32_SYSCALL::LISTEN:
    return SysCallId::LISTEN;

  case AMD64_SYSCALL::GETSOCKNAME:
  // case AMD64_X32_SYSCALL::GETSOCKNAME:
    return SysCallId::GETSOCKNAME;

  case AMD64_SYSCALL::GETPEERNAME:
  // case AMD64_X32_SYSCALL::GETPEERNAME:
    return SysCallId::GETPEERNAME;

  case AMD64_SYSCALL::SOCKETPAIR:
  // case AMD64_X32_SYSCALL::SOCKETPAIR:
    return SysCallId::SOCKETPAIR;

  case AMD64_SYSCALL::SETSOCKOPT:
  // case AMD64_X32_SYSCALL::SETSOCKOPT:
    return SysCallId::SETSOCKOPT;

  case AMD64_SYSCALL::GETSOCKOPT:
  // case AMD64_X32_SYSCALL::GETSOCKOPT:
    return SysCallId::GETSOCKOPT;

  case AMD64_SYSCALL::CLONE:
  // case AMD64_X32_SYSCALL::CLONE:
    return SysCallId::CLONE;

  case AMD64_SYSCALL::FORK:
  // case AMD64_X32_SYSCALL::FORK:
    return SysCallId::FORK;

  case AMD64_SYSCALL::VFORK:
  // case AMD64_X32_SYSCALL::VFORK:
    return SysCallId::VFORK;

  case AMD64_SYSCALL::EXECVE:
  // case AMD64_X32_SYSCALL::EXECVE:
    return SysCallId::EXECVE;

  case AMD64_SYSCALL::EXIT:
  // case AMD64_X32_SYSCALL::EXIT:
    return SysCallId::EXIT;

  case AMD64_SYSCALL::WAIT4:
  // case AMD64_X32_SYSCALL::WAIT4:
    return SysCallId::WAIT4;

  case AMD64_SYSCALL::KILL:
  // case AMD64_X32_SYSCALL::KILL:
    return SysCallId::KILL;

  case AMD64_SYSCALL::UNAME:
  // case AMD64_X32_SYSCALL::UNAME:
    return SysCallId::UNAME;

  case AMD64_SYSCALL::SEMGET:
  // case AMD64_X32_SYSCALL::SEMGET:
    return SysCallId::SEMGET;

  case AMD64_SYSCALL::SEMOP:
  // case AMD64_X32_SYSCALL::SEMOP:
    return SysCallId::SEMOP;

  case AMD64_SYSCALL::SEMCTL:
  // case AMD64_X32_SYSCALL::SEMCTL:
    return SysCallId::SEMCTL;

  case AMD64_SYSCALL::SHMDT:
  // case AMD64_X32_SYSCALL::SHMDT:
    return SysCallId::SHMDT;

  case AMD64_SYSCALL::MSGGET:
  // case AMD64_X32_SYSCALL::MSGGET:
    return SysCallId::MSGGET;

  case AMD64_SYSCALL::MSGSND:
  // case AMD64_X32_SYSCALL::MSGSND:
    return SysCallId::MSGSND;

  case AMD64_SYSCALL::MSGRCV:
  // case AMD64_X32_SYSCALL::MSGRCV:
    return SysCallId::MSGRCV;

  case AMD64_SYSCALL::MSGCTL:
  // case AMD64_X32_SYSCALL::MSGCTL:
    return SysCallId::MSGCTL;

  case AMD64_SYSCALL::FCNTL:
  // case AMD64_X32_SYSCALL::FCNTL:
    return SysCallId::FCNTL;

  case AMD64_SYSCALL::FLOCK:
  // case AMD64_X32_SYSCALL::FLOCK:
    return SysCallId::FLOCK;

  case AMD64_SYSCALL::FSYNC:
  // case AMD64_X32_SYSCALL::FSYNC:
    return SysCallId::FSYNC;

  case AMD64_SYSCALL::FDATASYNC:
  // case AMD64_X32_SYSCALL::FDATASYNC:
    return SysCallId::FDATASYNC;

  case AMD64_SYSCALL::TRUNCATE:
  // case AMD64_X32_SYSCALL::TRUNCATE:
    return SysCallId::TRUNCATE;

  case AMD64_SYSCALL::FTRUNCATE:
  // case AMD64_X32_SYSCALL::FTRUNCATE:
    return SysCallId::FTRUNCATE;

  case AMD64_SYSCALL::GETDENTS:
  // case AMD64_X32_SYSCALL::GETDENTS:
    return SysCallId::GETDENTS;

  case AMD64_SYSCALL::GETCWD:
  // case AMD64_X32_SYSCALL::GETCWD:
    return SysCallId::GETCWD;

  case AMD64_SYSCALL::CHDIR:
  // case AMD64_X32_SYSCALL::CHDIR:
    return SysCallId::CHDIR;

  case AMD64_SYSCALL::FCHDIR:
  // case AMD64_X32_SYSCALL::FCHDIR:
    return SysCallId::FCHDIR;

  case AMD64_SYSCALL::RENAME:
  // case AMD64_X32_SYSCALL::RENAME:
    return SysCallId::RENAME;

  case AMD64_SYSCALL::MKDIR:
  // case AMD64_X32_SYSCALL::MKDIR:
    return SysCallId::MKDIR;

  case AMD64_SYSCALL::RMDIR:
  // case AMD64_X32_SYSCALL::RMDIR:
    return SysCallId::RMDIR;

  case AMD64_SYSCALL::CREAT:
  // case AMD64_X32_SYSCALL::CREAT:
    return SysCallId::CREAT;

  case AMD64_SYSCALL::LINK:
  // case AMD64_X32_SYSCALL::LINK:
    return SysCallId::LINK;

  case AMD64_SYSCALL::UNLINK:
  // case AMD64_X32_SYSCALL::UNLINK:
    return SysCallId::UNLINK;

  case AMD64_SYSCALL::SYMLINK:
  // case AMD64_X32_SYSCALL::SYMLINK:
    return SysCallId::SYMLINK;

  case AMD64_SYSCALL::READLINK:
  // case AMD64_X32_SYSCALL::READLINK:
    return SysCallId::READLINK;

  case AMD64_SYSCALL::CHMOD:
  // case AMD64_X32_SYSCALL::CHMOD:
    return SysCallId::CHMOD;

  case AMD64_SYSCALL::FCHMOD:
  // case AMD64_X32_SYSCALL::FCHMOD:
    return SysCallId::FCHMOD;

  case AMD64_SYSCALL::CHOWN:
  // case AMD64_X32_SYSCALL::CHOWN:
    return SysCallId::CHOWN;

  case AMD64_SYSCALL::FCHOWN:
  // case AMD64_X32_SYSCALL::FCHOWN:
    return SysCallId::FCHOWN;

  case AMD64_SYSCALL::LCHOWN:
  // case AMD64_X32_SYSCALL::LCHOWN:
    return SysCallId::LCHOWN;

  case AMD64_SYSCALL::UMASK:
  // case AMD64_X32_SYSCALL::UMASK:
    return SysCallId::UMASK;

  case AMD64_SYSCALL::GETTIMEOFDAY:
  // case AMD64_X32_SYSCALL::GETTIMEOFDAY:
    return SysCallId::GETTIMEOFDAY;

  case AMD64_SYSCALL::GETRLIMIT:
  // case AMD64_X32_SYSCALL::GETRLIMIT:
    return SysCallId::GETRLIMIT;

  case AMD64_SYSCALL::GETRUSAGE:
  // case AMD64_X32_SYSCALL::GETRUSAGE:
    return SysCallId::GETRUSAGE;

  case AMD64_SYSCALL::SYSINFO:
  // case AMD64_X32_SYSCALL::NFO:
    return SysCallId::SYSINFO;

  case AMD64_SYSCALL::TIMES:
  // case AMD64_X32_SYSCALL::TIMES:
    return SysCallId::TIMES;

  case AMD64_SYSCALL::PTRACE:
  // case AMD64_X32_SYSCALL::PTRACE:
    return SysCallId::PTRACE;

  case AMD64_SYSCALL::GETUID:
  // case AMD64_X32_SYSCALL::GETUID:
    return SysCallId::GETUID;

  case AMD64_SYSCALL::SYSLOG:
  // case AMD64_X32_SYSCALL::SYSLOG:
    return SysCallId::SYSLOG;

  case AMD64_SYSCALL::GETGID:
  // case AMD64_X32_SYSCALL::GETGID:
    return SysCallId::GETGID;

  case AMD64_SYSCALL::SETUID:
  // case AMD64_X32_SYSCALL::SETUID:
    return SysCallId::SETUID;

  case AMD64_SYSCALL::SETGID:
  // case AMD64_X32_SYSCALL::SETGID:
    return SysCallId::SETGID;

  case AMD64_SYSCALL::GETEUID:
  // case AMD64_X32_SYSCALL::GETEUID:
    return SysCallId::GETEUID;

  case AMD64_SYSCALL::GETEGID:
  // case AMD64_X32_SYSCALL::GETEGID:
    return SysCallId::GETEGID;

  case AMD64_SYSCALL::SETPGID:
  // case AMD64_X32_SYSCALL::SETPGID:
    return SysCallId::SETPGID;

  case AMD64_SYSCALL::GETPPID:
  // case AMD64_X32_SYSCALL::GETPPID:
    return SysCallId::GETPPID;

  case AMD64_SYSCALL::GETPGRP:
  // case AMD64_X32_SYSCALL::GETPGRP:
    return SysCallId::GETPGRP;

  case AMD64_SYSCALL::SETSID:
  // case AMD64_X32_SYSCALL::SETSID:
    return SysCallId::SETSID;

  case AMD64_SYSCALL::SETREUID:
  // case AMD64_X32_SYSCALL::SETREUID:
    return SysCallId::SETREUID;

  case AMD64_SYSCALL::SETREGID:
  // case AMD64_X32_SYSCALL::SETREGID:
    return SysCallId::SETREGID;

  case AMD64_SYSCALL::GETGROUPS:
  // case AMD64_X32_SYSCALL::GETGROUPS:
    return SysCallId::GETGROUPS;

  case AMD64_SYSCALL::SETGROUPS:
  // case AMD64_X32_SYSCALL::SETGROUPS:
    return SysCallId::SETGROUPS;

  case AMD64_SYSCALL::SETRESUID:
  // case AMD64_X32_SYSCALL::SETRESUID:
    return SysCallId::SETRESUID;

  case AMD64_SYSCALL::GETRESUID:
  // case AMD64_X32_SYSCALL::GETRESUID:
    return SysCallId::GETRESUID;

  case AMD64_SYSCALL::SETRESGID:
  // case AMD64_X32_SYSCALL::SETRESGID:
    return SysCallId::SETRESGID;

  case AMD64_SYSCALL::GETRESGID:
  // case AMD64_X32_SYSCALL::GETRESGID:
    return SysCallId::GETRESGID;

  case AMD64_SYSCALL::GETPGID:
  // case AMD64_X32_SYSCALL::GETPGID:
    return SysCallId::GETPGID;

  case AMD64_SYSCALL::SETFSUID:
  // case AMD64_X32_SYSCALL::SETFSUID:
    return SysCallId::SETFSUID;

  case AMD64_SYSCALL::SETFSGID:
  // case AMD64_X32_SYSCALL::SETFSGID:
    return SysCallId::SETFSGID;

  case AMD64_SYSCALL::GETSID:
  // case AMD64_X32_SYSCALL::GETSID:
    return SysCallId::GETSID;

  case AMD64_SYSCALL::CAPGET:
  // case AMD64_X32_SYSCALL::CAPGET:
    return SysCallId::CAPGET;

  case AMD64_SYSCALL::CAPSET:
  // case AMD64_X32_SYSCALL::CAPSET:
    return SysCallId::CAPSET;

  case AMD64_SYSCALL::RT_SIGPENDING:
  // case AMD64_X32_SYSCALL::RT_SIGPENDING:
    return SysCallId::RT_SIGPENDING;

  case AMD64_SYSCALL::RT_SIGTIMEDWAIT:
  // case AMD64_X32_SYSCALL::RT_SIGTIMEDWAIT:
    return SysCallId::RT_SIGTIMEDWAIT;

  case AMD64_SYSCALL::RT_SIGQUEUEINFO:
  // case AMD64_X32_SYSCALL::RT_SIGQUEUEINFO:
    return SysCallId::RT_SIGQUEUEINFO;

  case AMD64_SYSCALL::RT_SIGSUSPEND:
  // case AMD64_X32_SYSCALL::RT_SIGSUSPEND:
    return SysCallId::RT_SIGSUSPEND;

  case AMD64_SYSCALL::SIGALTSTACK:
  // case AMD64_X32_SYSCALL::SIGALTSTACK:
    return SysCallId::SIGALTSTACK;

  case AMD64_SYSCALL::UTIME:
  // case AMD64_X32_SYSCALL::UTIME:
    return SysCallId::UTIME;

  case AMD64_SYSCALL::MKNOD:
  // case AMD64_X32_SYSCALL::MKNOD:
    return SysCallId::MKNOD;

  case AMD64_SYSCALL::PERSONALITY:
  // case AMD64_X32_SYSCALL::PERSONALITY:
    return SysCallId::PERSONALITY;

  case AMD64_SYSCALL::USTAT:
  // case AMD64_X32_SYSCALL::USTAT:
    return SysCallId::USTAT;

  case AMD64_SYSCALL::STATFS:
  // case AMD64_X32_SYSCALL::STATFS:
    return SysCallId::STATFS;

  case AMD64_SYSCALL::FSTATFS:
  // case AMD64_X32_SYSCALL::FSTATFS:
    return SysCallId::FSTATFS;

  case AMD64_SYSCALL::SYSFS:
  // case AMD64_X32_SYSCALL::S:
    return SysCallId::SYSFS;

  case AMD64_SYSCALL::GETPRIORITY:
  // case AMD64_X32_SYSCALL::GETPRIORITY:
    return SysCallId::GETPRIORITY;

  case AMD64_SYSCALL::SETPRIORITY:
  // case AMD64_X32_SYSCALL::SETPRIORITY:
    return SysCallId::SETPRIORITY;

  case AMD64_SYSCALL::SCHED_SETPARAM:
  // case AMD64_X32_SYSCALL::SCHED_SETPARAM:
    return SysCallId::SCHED_SETPARAM;

  case AMD64_SYSCALL::SCHED_GETPARAM:
  // case AMD64_X32_SYSCALL::SCHED_GETPARAM:
    return SysCallId::SCHED_GETPARAM;

  case AMD64_SYSCALL::SCHED_SETSCHEDULER:
  // case AMD64_X32_SYSCALL::SCHED_SETSCHEDULER:
    return SysCallId::SCHED_SETSCHEDULER;

  case AMD64_SYSCALL::SCHED_GETSCHEDULER:
  // case AMD64_X32_SYSCALL::SCHED_GETSCHEDULER:
    return SysCallId::SCHED_GETSCHEDULER;

  case AMD64_SYSCALL::SCHED_GET_PRIORITY_MAX:
  // case AMD64_X32_SYSCALL::SCHED_GET_PRIORITY_MAX:
    return SysCallId::SCHED_GET_PRIORITY_MAX;

  case AMD64_SYSCALL::SCHED_GET_PRIORITY_MIN:
  // case AMD64_X32_SYSCALL::SCHED_GET_PRIORITY_MIN:
    return SysCallId::SCHED_GET_PRIORITY_MIN;

  case AMD64_SYSCALL::SCHED_RR_GET_INTERVAL:
  // case AMD64_X32_SYSCALL::SCHED_RR_GET_INTERVAL:
    return SysCallId::SCHED_RR_GET_INTERVAL;

  case AMD64_SYSCALL::MLOCK:
  // case AMD64_X32_SYSCALL::MLOCK:
    return SysCallId::MLOCK;

  case AMD64_SYSCALL::MUNLOCK:
  // case AMD64_X32_SYSCALL::MUNLOCK:
    return SysCallId::MUNLOCK;

  case AMD64_SYSCALL::MLOCKALL:
  // case AMD64_X32_SYSCALL::MLOCKALL:
    return SysCallId::MLOCKALL;

  case AMD64_SYSCALL::MUNLOCKALL:
  // case AMD64_X32_SYSCALL::MUNLOCKALL:
    return SysCallId::MUNLOCKALL;

  case AMD64_SYSCALL::VHANGUP:
  // case AMD64_X32_SYSCALL::VHANGUP:
    return SysCallId::VHANGUP;

  case AMD64_SYSCALL::MODIFY_LDT:
  // case AMD64_X32_SYSCALL::MODIFY_LDT:
    return SysCallId::MODIFY_LDT;

  case AMD64_SYSCALL::PIVOT_ROOT:
  // case AMD64_X32_SYSCALL::PIVOT_ROOT:
    return SysCallId::PIVOT_ROOT;

  case AMD64_SYSCALL::SYSCTL:
  // case AMD64_X32_SYSCALL::TL:
    return SysCallId::SYSCTL;

  case AMD64_SYSCALL::PRCTL:
  // case AMD64_X32_SYSCALL::PRCTL:
    return SysCallId::PRCTL;

  case AMD64_SYSCALL::ARCH_PRCTL:
  // case AMD64_X32_SYSCALL::ARCH_PRCTL:
    return SysCallId::ARCH_PRCTL;	/* Note */

  case AMD64_SYSCALL::ADJTIMEX:
  // case AMD64_X32_SYSCALL::ADJTIMEX:
    return SysCallId::ADJTIMEX;

  case AMD64_SYSCALL::SETRLIMIT:
  // case AMD64_X32_SYSCALL::SETRLIMIT:
    return SysCallId::SETRLIMIT;

  case AMD64_SYSCALL::CHROOT:
  // case AMD64_X32_SYSCALL::CHROOT:
    return SysCallId::CHROOT;

  case AMD64_SYSCALL::SYNC:
  // case AMD64_X32_SYSCALL::SYNC:
    return SysCallId::SYNC;

  case AMD64_SYSCALL::ACCT:
  // case AMD64_X32_SYSCALL::ACCT:
    return SysCallId::ACCT;

  case AMD64_SYSCALL::SETTIMEOFDAY:
  // case AMD64_X32_SYSCALL::SETTIMEOFDAY:
    return SysCallId::SETTIMEOFDAY;

  case AMD64_SYSCALL::MOUNT:
  // case AMD64_X32_SYSCALL::MOUNT:
    return SysCallId::MOUNT;

  case AMD64_SYSCALL::UMOUNT:
  // case AMD64_X32_SYSCALL::UMOUNT:
    return SysCallId::UMOUNT;

  case AMD64_SYSCALL::SWAPON:
  // case AMD64_X32_SYSCALL::SWAPON:
    return SysCallId::SWAPON;

  case AMD64_SYSCALL::SWAPOFF:
  // case AMD64_X32_SYSCALL::SWAPOFF:
    return SysCallId::SWAPOFF;

  case AMD64_SYSCALL::REBOOT:
  // case AMD64_X32_SYSCALL::REBOOT:
    return SysCallId::REBOOT;

  case AMD64_SYSCALL::SETHOSTNAME:
  // case AMD64_X32_SYSCALL::SETHOSTNAME:
    return SysCallId::SETHOSTNAME;

  case AMD64_SYSCALL::SETDOMAINNAME:
  // case AMD64_X32_SYSCALL::SETDOMAINNAME:
    return SysCallId::SETDOMAINNAME;

  case AMD64_SYSCALL::IOPL:
  // case AMD64_X32_SYSCALL::IOPL:
    return SysCallId::IOPL;

  case AMD64_SYSCALL::IOPERM:
  // case AMD64_X32_SYSCALL::IOPERM:
    return SysCallId::IOPERM;

  case AMD64_SYSCALL::INIT_MODULE:
  // case AMD64_X32_SYSCALL::INIT_MODULE:
    return SysCallId::INIT_MODULE;

  case AMD64_SYSCALL::DELETE_MODULE:
  // case AMD64_X32_SYSCALL::DELETE_MODULE:
    return SysCallId::DELETE_MODULE;

  case AMD64_SYSCALL::QUOTACTL:
  // case AMD64_X32_SYSCALL::QUOTACTL:
    return SysCallId::QUOTACTL;

  case AMD64_SYSCALL::NFSSERVCTL:
    return SysCallId::NFSSERVCTL;

  case AMD64_SYSCALL::GETTID:
  // case AMD64_X32_SYSCALL::GETTID:
    return SysCallId::GETTID;

  case AMD64_SYSCALL::READAHEAD:
  // case AMD64_X32_SYSCALL::READAHEAD:
    return SysCallId::READAHEAD;

  case AMD64_SYSCALL::SETXATTR:
  // case AMD64_X32_SYSCALL::SETXATTR:
    return SysCallId::SETXATTR;

  case AMD64_SYSCALL::LSETXATTR:
  // case AMD64_X32_SYSCALL::LSETXATTR:
    return SysCallId::LSETXATTR;

  case AMD64_SYSCALL::FSETXATTR:
  // case AMD64_X32_SYSCALL::FSETXATTR:
    return SysCallId::FSETXATTR;

  case AMD64_SYSCALL::GETXATTR:
  // case AMD64_X32_SYSCALL::GETXATTR:
    return SysCallId::GETXATTR;

  case AMD64_SYSCALL::LGETXATTR:
  // case AMD64_X32_SYSCALL::LGETXATTR:
    return SysCallId::LGETXATTR;

  case AMD64_SYSCALL::FGETXATTR:
  // case AMD64_X32_SYSCALL::FGETXATTR:
    return SysCallId::FGETXATTR;

  case AMD64_SYSCALL::LISTXATTR:
  // case AMD64_X32_SYSCALL::LISTXATTR:
    return SysCallId::LISTXATTR;

  case AMD64_SYSCALL::LLISTXATTR:
  // case AMD64_X32_SYSCALL::LLISTXATTR:
    return SysCallId::LLISTXATTR;

  case AMD64_SYSCALL::FLISTXATTR:
  // case AMD64_X32_SYSCALL::FLISTXATTR:
    return SysCallId::FLISTXATTR;

  case AMD64_SYSCALL::REMOVEXATTR:
  // case AMD64_X32_SYSCALL::REMOVEXATTR:
    return SysCallId::REMOVEXATTR;

  case AMD64_SYSCALL::LREMOVEXATTR:
  // case AMD64_X32_SYSCALL::LREMOVEXATTR:
    return SysCallId::LREMOVEXATTR;

  case AMD64_SYSCALL::FREMOVEXATTR:
  // case AMD64_X32_SYSCALL::FREMOVEXATTR:
    return SysCallId::FREMOVEXATTR;

  case AMD64_SYSCALL::TKILL:
  // case AMD64_X32_SYSCALL::TKILL:
    return SysCallId::TKILL;

  case AMD64_SYSCALL::TIME:
  // case AMD64_X32_SYSCALL::TIME:
    return SysCallId::TIME;

  case AMD64_SYSCALL::FUTEX:
  // case AMD64_X32_SYSCALL::FUTEX:
    return SysCallId::FUTEX;

  case AMD64_SYSCALL::SCHED_SETAFFINITY:
  // case AMD64_X32_SYSCALL::SCHED_SETAFFINITY:
    return SysCallId::SCHED_SETAFFINITY;

  case AMD64_SYSCALL::SCHED_GETAFFINITY:
  // case AMD64_X32_SYSCALL::SCHED_GETAFFINITY:
    return SysCallId::SCHED_GETAFFINITY;

  case AMD64_SYSCALL::IO_SETUP:
  // case AMD64_X32_SYSCALL::IO_SETUP:
    return SysCallId::IO_SETUP;

  case AMD64_SYSCALL::IO_DESTROY:
  // case AMD64_X32_SYSCALL::IO_DESTROY:
    return SysCallId::IO_DESTROY;

  case AMD64_SYSCALL::IO_GETEVENTS:
  // case AMD64_X32_SYSCALL::IO_GETEVENTS:
    return SysCallId::IO_GETEVENTS;

  case AMD64_SYSCALL::IO_SUBMIT:
  // case AMD64_X32_SYSCALL::IO_SUBMIT:
    return SysCallId::IO_SUBMIT;

  case AMD64_SYSCALL::IO_CANCEL:
  // case AMD64_X32_SYSCALL::IO_CANCEL:
    return SysCallId::IO_CANCEL;

  case AMD64_SYSCALL::LOOKUP_DCOOKIE:
  // case AMD64_X32_SYSCALL::LOOKUP_DCOOKIE:
    return SysCallId::LOOKUP_DCOOKIE;

  case AMD64_SYSCALL::EPOLL_CREATE:
  // case AMD64_X32_SYSCALL::EPOLL_CREATE:
    return SysCallId::EPOLL_CREATE;

  case AMD64_SYSCALL::REMAP_FILE_PAGES:
  // case AMD64_X32_SYSCALL::REMAP_FILE_PAGES:
    return SysCallId::REMAP_FILE_PAGES;

  case AMD64_SYSCALL::GETDENTS64:
  // case AMD64_X32_SYSCALL::GETDENTS64:
    return SysCallId::GETDENTS64;

  case AMD64_SYSCALL::SET_TID_ADDRESS:
  // case AMD64_X32_SYSCALL::SET_TID_ADDRESS:
    return SysCallId::SET_TID_ADDRESS;

  case AMD64_SYSCALL::RESTART_SYSCALL:
  // case AMD64_X32_SYSCALL::RESTART_SYSCALL:
    return SysCallId::RESTART_SYSCALL;

  case AMD64_SYSCALL::SEMTIMEDOP:
  // case AMD64_X32_SYSCALL::SEMTIMEDOP:
    return SysCallId::SEMTIMEDOP;

  case AMD64_SYSCALL::FADVISE64:
  // case AMD64_X32_SYSCALL::FADVISE64:
    return SysCallId::FADVISE64;

  case AMD64_SYSCALL::TIMER_CREATE:
  // case AMD64_X32_SYSCALL::TIMER_CREATE:
    return SysCallId::TIMER_CREATE;

  case AMD64_SYSCALL::TIMER_SETTIME:
  // case AMD64_X32_SYSCALL::TIMER_SETTIME:
    return SysCallId::TIMER_SETTIME;

  case AMD64_SYSCALL::TIMER_GETTIME:
  // case AMD64_X32_SYSCALL::TIMER_GETTIME:
    return SysCallId::TIMER_GETTIME;

  case AMD64_SYSCALL::TIMER_GETOVERRUN:
  // case AMD64_X32_SYSCALL::TIMER_GETOVERRUN:
    return SysCallId::TIMER_GETOVERRUN;

  case AMD64_SYSCALL::TIMER_DELETE:
  // case AMD64_X32_SYSCALL::TIMER_DELETE:
    return SysCallId::TIMER_DELETE;

  case AMD64_SYSCALL::CLOCK_SETTIME:
  // case AMD64_X32_SYSCALL::CLOCK_SETTIME:
    return SysCallId::CLOCK_SETTIME;

  case AMD64_SYSCALL::CLOCK_GETTIME:
  // case AMD64_X32_SYSCALL::CLOCK_GETTIME:
    return SysCallId::CLOCK_GETTIME;

  case AMD64_SYSCALL::CLOCK_GETRES:
  // case AMD64_X32_SYSCALL::CLOCK_GETRES:
    return SysCallId::CLOCK_GETRES;

  case AMD64_SYSCALL::CLOCK_NANOSLEEP:
  // case AMD64_X32_SYSCALL::CLOCK_NANOSLEEP:
    return SysCallId::CLOCK_NANOSLEEP;

  case AMD64_SYSCALL::EXIT_GROUP:
  // case AMD64_X32_SYSCALL::EXIT_GROUP:
    return SysCallId::EXIT_GROUP;

  case AMD64_SYSCALL::EPOLL_WAIT:
  // case AMD64_X32_SYSCALL::EPOLL_WAIT:
    return SysCallId::EPOLL_WAIT;

  case AMD64_SYSCALL::EPOLL_CTL:
  // case AMD64_X32_SYSCALL::EPOLL_CTL:
    return SysCallId::EPOLL_CTL;

  case AMD64_SYSCALL::TGKILL:
  // case AMD64_X32_SYSCALL::TGKILL:
    return SysCallId::TGKILL;

  case AMD64_SYSCALL::UTIMES:
  // case AMD64_X32_SYSCALL::UTIMES:
    return SysCallId::UTIMES;

  case AMD64_SYSCALL::MBIND:
  // case AMD64_X32_SYSCALL::MBIND:
    return SysCallId::MBIND;

  case AMD64_SYSCALL::SET_MEMPOLICY:
  // case AMD64_X32_SYSCALL::SET_MEMPOLICY:
    return SysCallId::SET_MEMPOLICY;

  case AMD64_SYSCALL::GET_MEMPOLICY:
  // case AMD64_X32_SYSCALL::GET_MEMPOLICY:
    return SysCallId::GET_MEMPOLICY;

  case AMD64_SYSCALL::MQ_OPEN:
  // case AMD64_X32_SYSCALL::MQ_OPEN:
    return SysCallId::MQ_OPEN;

  case AMD64_SYSCALL::MQ_UNLINK:
  // case AMD64_X32_SYSCALL::MQ_UNLINK:
    return SysCallId::MQ_UNLINK;

  case AMD64_SYSCALL::MQ_TIMEDSEND:
  // case AMD64_X32_SYSCALL::MQ_TIMEDSEND:
    return SysCallId::MQ_TIMEDSEND;

  case AMD64_SYSCALL::MQ_TIMEDRECEIVE:
  // case AMD64_X32_SYSCALL::MQ_TIMEDRECEIVE:
    return SysCallId::MQ_TIMEDRECEIVE;

  case AMD64_SYSCALL::MQ_NOTIFY:
  // case AMD64_X32_SYSCALL::MQ_NOTIFY:
    return SysCallId::MQ_NOTIFY;

  case AMD64_SYSCALL::MQ_GETSETATTR:
  // case AMD64_X32_SYSCALL::MQ_GETSETATTR:
    return SysCallId::MQ_GETSETATTR;

  case AMD64_SYSCALL::KEXEC_LOAD:
  // case AMD64_X32_SYSCALL::KEXEC_LOAD:
    return SysCallId::KEXEC_LOAD;

  case AMD64_SYSCALL::WAITID:
  // case AMD64_X32_SYSCALL::WAITID:
    return SysCallId::WAITID;

  case AMD64_SYSCALL::ADD_KEY:
  // case AMD64_X32_SYSCALL::ADD_KEY:
    return SysCallId::ADD_KEY;

  case AMD64_SYSCALL::REQUEST_KEY:
  // case AMD64_X32_SYSCALL::REQUEST_KEY:
    return SysCallId::REQUEST_KEY;

  case AMD64_SYSCALL::KEYCTL:
  // case AMD64_X32_SYSCALL::KEYCTL:
    return SysCallId::KEYCTL;

  case AMD64_SYSCALL::IOPRIO_SET:
  // case AMD64_X32_SYSCALL::IOPRIO_SET:
    return SysCallId::IOPRIO_SET;

  case AMD64_SYSCALL::IOPRIO_GET:
  // case AMD64_X32_SYSCALL::IOPRIO_GET:
    return SysCallId::IOPRIO_GET;

  case AMD64_SYSCALL::INOTIFY_INIT:
  // case AMD64_X32_SYSCALL::INOTIFY_INIT:
    return SysCallId::INOTIFY_INIT;

  case AMD64_SYSCALL::INOTIFY_ADD_WATCH:
  // case AMD64_X32_SYSCALL::INOTIFY_ADD_WATCH:
    return SysCallId::INOTIFY_ADD_WATCH;

  case AMD64_SYSCALL::INOTIFY_RM_WATCH:
  // case AMD64_X32_SYSCALL::INOTIFY_RM_WATCH:
    return SysCallId::INOTIFY_RM_WATCH;

  case AMD64_SYSCALL::MIGRATE_PAGES:
  // case AMD64_X32_SYSCALL::MIGRATE_PAGES:
    return SysCallId::MIGRATE_PAGES;

  case AMD64_SYSCALL::OPENAT:
  // case AMD64_X32_SYSCALL::OPENAT:
    return SysCallId::OPENAT;

  case AMD64_SYSCALL::MKDIRAT:
  // case AMD64_X32_SYSCALL::MKDIRAT:
    return SysCallId::MKDIRAT;

  case AMD64_SYSCALL::MKNODAT:
  // case AMD64_X32_SYSCALL::MKNODAT:
    return SysCallId::MKNODAT;

  case AMD64_SYSCALL::FCHOWNAT:
  // case AMD64_X32_SYSCALL::FCHOWNAT:
    return SysCallId::FCHOWNAT;

  case AMD64_SYSCALL::FUTIMESAT:
  // case AMD64_X32_SYSCALL::FUTIMESAT:
    return SysCallId::FUTIMESAT;

  case AMD64_SYSCALL::NEWFSTATAT:
  // case AMD64_X32_SYSCALL::NEWFSTATAT:
    return SysCallId::NEWFSTATAT;

  case AMD64_SYSCALL::UNLINKAT:
  // case AMD64_X32_SYSCALL::UNLINKAT:
    return SysCallId::UNLINKAT;

  case AMD64_SYSCALL::RENAMEAT:
  // case AMD64_X32_SYSCALL::RENAMEAT:
    return SysCallId::RENAMEAT;

  case AMD64_SYSCALL::LINKAT:
  // case AMD64_X32_SYSCALL::LINKAT:
    return SysCallId::LINKAT;

  case AMD64_SYSCALL::SYMLINKAT:
  // case AMD64_X32_SYSCALL::SYMLINKAT:
    return SysCallId::SYMLINKAT;

  case AMD64_SYSCALL::READLINKAT:
  // case AMD64_X32_SYSCALL::READLINKAT:
    return SysCallId::READLINKAT;

  case AMD64_SYSCALL::FCHMODAT:
  // case AMD64_X32_SYSCALL::FCHMODAT:
    return SysCallId::FCHMODAT;

  case AMD64_SYSCALL::FACCESSAT:
  // case AMD64_X32_SYSCALL::FACCESSAT:
    return SysCallId::FACCESSAT;

  case AMD64_SYSCALL::PSELECT6:
  // case AMD64_X32_SYSCALL::PSELECT6:
    return SysCallId::PSELECT6;

  case AMD64_SYSCALL::PPOLL:
  // case AMD64_X32_SYSCALL::PPOLL:
    return SysCallId::PPOLL;

  case AMD64_SYSCALL::UNSHARE:
  // case AMD64_X32_SYSCALL::UNSHARE:
    return SysCallId::UNSHARE;

  case AMD64_SYSCALL::SET_ROBUST_LIST:
  // case AMD64_X32_SYSCALL::SET_ROBUST_LIST:
    return SysCallId::SET_ROBUST_LIST;

  case AMD64_SYSCALL::GET_ROBUST_LIST:
  // case AMD64_X32_SYSCALL::GET_ROBUST_LIST:
    return SysCallId::GET_ROBUST_LIST;

  case AMD64_SYSCALL::SPLICE:
  // case AMD64_X32_SYSCALL::SPLICE:
    return SysCallId::SPLICE;

  case AMD64_SYSCALL::TEE:
  // case AMD64_X32_SYSCALL::TEE:
    return SysCallId::TEE;

  case AMD64_SYSCALL::SYNC_FILE_RANGE:
  // case AMD64_X32_SYSCALL::SYNC_FILE_RANGE:
    return SysCallId::SYNC_FILE_RANGE;

  case AMD64_SYSCALL::VMSPLICE:
  // case AMD64_X32_SYSCALL::VMSPLICE:
    return SysCallId::VMSPLICE;

  case AMD64_SYSCALL::MOVE_PAGES:
  // case AMD64_X32_SYSCALL::MOVE_PAGES:
    return SysCallId::MOVE_PAGES;

  default:
    return SysCallId::NO_SYSCALL;
  }

}