#ifndef _SYS_COFNIG_H
#define _SYS_COFNIG_H


#define SHAMAN_LOG_LEVEL_TRACE 0
#define SHAMAN_LOG_LEVEL_DEBUG 1
#define SHAMAN_LOG_LEVEL_INFO 2
#define SHAMAN_LOG_LEVEL_WARN 3
#define SHAMAN_LOG_LEVEL_ERROR 4
#define SHAMAN_LOG_LEVEL_CRITICAL 5
#define SHAMAN_LOG_LEVEL_OFF 6

#define SUPPORT_ARCH_ARM

#define SPDLOG_ACTIVE_LEVEL SHAMAN_LOG_LEVEL_TRACE

// #define SUPPORT_MEM_FILE 1

#endif